services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web-blogs-app
    restart: always
    ports:
      - "3003:3000"

    # ดึง Environment Variables ทั้งหมดจากไฟล์ .env (Portainer จะสร้างไฟล์ .env นี้ให้อัตโนมัติจาก GUI)
    env_file:
      - .env

    environment:
      - PORT=3000
      - HOSTNAME=0.0.0.0

    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - service_api_net
      - default

networks:
  service_api_net:
    external: true
    name: service-webblog-api_default
